# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import replication_pb2 as replication__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in replication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReplicationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClientWrite = channel.unary_unary(
                '/replication.Replication/ClientWrite',
                request_serializer=replication__pb2.ClientWriteRequest.SerializeToString,
                response_deserializer=replication__pb2.ClientWriteResponse.FromString,
                _registered_method=True)
        self.ClientRead = channel.unary_unary(
                '/replication.Replication/ClientRead',
                request_serializer=replication__pb2.ClientReadRequest.SerializeToString,
                response_deserializer=replication__pb2.ClientReadResponse.FromString,
                _registered_method=True)
        self.AppendEntries = channel.unary_unary(
                '/replication.Replication/AppendEntries',
                request_serializer=replication__pb2.AppendEntriesRequest.SerializeToString,
                response_deserializer=replication__pb2.AppendEntriesResponse.FromString,
                _registered_method=True)
        self.CommitEntry = channel.unary_unary(
                '/replication.Replication/CommitEntry',
                request_serializer=replication__pb2.CommitRequest.SerializeToString,
                response_deserializer=replication__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.Sync = channel.unary_unary(
                '/replication.Replication/Sync',
                request_serializer=replication__pb2.SyncRequest.SerializeToString,
                response_deserializer=replication__pb2.SyncResponse.FromString,
                _registered_method=True)
        self.SyncEntries = channel.unary_unary(
                '/replication.Replication/SyncEntries',
                request_serializer=replication__pb2.SyncResponse.SerializeToString,
                response_deserializer=replication__pb2.SyncEntriesResponse.FromString,
                _registered_method=True)


class ReplicationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClientWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitEntry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClientWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientWrite,
                    request_deserializer=replication__pb2.ClientWriteRequest.FromString,
                    response_serializer=replication__pb2.ClientWriteResponse.SerializeToString,
            ),
            'ClientRead': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientRead,
                    request_deserializer=replication__pb2.ClientReadRequest.FromString,
                    response_serializer=replication__pb2.ClientReadResponse.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=replication__pb2.AppendEntriesRequest.FromString,
                    response_serializer=replication__pb2.AppendEntriesResponse.SerializeToString,
            ),
            'CommitEntry': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitEntry,
                    request_deserializer=replication__pb2.CommitRequest.FromString,
                    response_serializer=replication__pb2.CommitResponse.SerializeToString,
            ),
            'Sync': grpc.unary_unary_rpc_method_handler(
                    servicer.Sync,
                    request_deserializer=replication__pb2.SyncRequest.FromString,
                    response_serializer=replication__pb2.SyncResponse.SerializeToString,
            ),
            'SyncEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncEntries,
                    request_deserializer=replication__pb2.SyncResponse.FromString,
                    response_serializer=replication__pb2.SyncEntriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'replication.Replication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('replication.Replication', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Replication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClientWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.Replication/ClientWrite',
            replication__pb2.ClientWriteRequest.SerializeToString,
            replication__pb2.ClientWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.Replication/ClientRead',
            replication__pb2.ClientReadRequest.SerializeToString,
            replication__pb2.ClientReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.Replication/AppendEntries',
            replication__pb2.AppendEntriesRequest.SerializeToString,
            replication__pb2.AppendEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitEntry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.Replication/CommitEntry',
            replication__pb2.CommitRequest.SerializeToString,
            replication__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.Replication/Sync',
            replication__pb2.SyncRequest.SerializeToString,
            replication__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.Replication/SyncEntries',
            replication__pb2.SyncResponse.SerializeToString,
            replication__pb2.SyncEntriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
