syntax = "proto3";

package replication;

service Replication {
    rpc ClientWrite(ClientWriteRequest) returns (ClientWriteResponse);

    rpc ClientRead(ClientReadRequest) returns (ClientReadResponse);

    rpc AppendEntries(AppendEntriesRequest) returns (AppendEntriesResponse);

    rpc CommitEntry(CommitRequest) returns (CommitResponse);
}

message LogEntry {
    int64 epoch = 1;
    int64 offset = 2;
    string data = 3;
}

message ClientWriteRequest {
    string data = 1;
}

message ClientWriteResponse {
    bool success = 1;
    string message = 2;
}

message ClientReadRequest {
}

message ClientReadResponse {
    optional string data = 1;
    int64 epoch = 2;
    int64 offset = 3;
    bool found = 4;
}


message AppendEntriesRequest {
    int64 leader_epoch = 1;
    LogEntry entry = 2;
}

message AppendEntriesResponse {
    bool success = 1;
    string replica_id = 2;
}

message CommitRequest {
    int64 epoch = 1;
    int64 offset = 2;
}

message CommitResponse {
    bool success = 1;
}