syntax = "proto3";

package replication;

service Replication {
    rpc ClientWrite(ClientWriteRequest) returns (ClientWriteResponse);
    rpc ClientRead(ClientReadRequest) returns (ClientReadResponse);
    rpc AppendEntries(AppendEntriesRequest) returns (AppendEntriesResponse);
    rpc CommitEntry(CommitRequest) returns (CommitResponse);
    rpc Sync(SyncRequest) returns (SyncResponse);
    rpc SyncEntries(SyncResponse) returns (SyncEntriesResponse);
}

message LogEntry {
    int64 epoch = 1;
    int64 offset = 2;
    string data = 3;
}

message ClientWriteRequest {
    string data = 1;
}

message ClientWriteResponse {
    bool success = 1;
    string message = 2;
}

message ClientReadRequest {
}

message ClientReadResponse {
    optional string data = 1;
    int64 epoch = 2;
    int64 offset = 3;
    bool found = 4;
}

message AppendEntriesRequest {
    int64 leader_epoch = 1;
    LogEntry entry = 2;
}

message AppendEntriesResponse {
    bool success = 1;
    string replica_id = 2;
    bool needs_sync = 3;
    int64 last_offset = 4;
}

message CommitRequest {
    int64 epoch = 1;
    int64 offset = 2;
}

message CommitResponse {
    bool success = 1;
}

message SyncRequest {
    string replica_id = 1;
    int64 last_offset = 2;
}

message SyncResponse {
    bool success = 1;
    repeated LogEntry entries = 2;
    int64 committed_offset = 3;
}

message SyncEntriesResponse {
    bool success = 1;
}